#
# Copyright (C) 2011 Evite LLC

# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.

# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

import os

from nudge.utils import Dict

from jinja2 import Environment, FileSystemLoader

template_dir = "/".join(__file__.split("/")[0:-1]) + "/templates" 
template_env = Environment(loader=FileSystemLoader(template_dir))

__all__ = [
    'get_template',
    'AutomagicGenerator',
]

def get_template(filename=None):
    assert filename, "I need a filename, smartypants"
    text=None
    filepath = os.path.join(template_dir, filename)
    assert os.path.exists(filepath), "The template file doesn't exist"
    text = open(filepath, "r").read()
    assert text, "How about some text"
    return template_env.get_template(filename)

class AutomagicGenerator(object):
    extension = 'txt'
    template = get_template('default.html')

    def __init__(self, dir='/tmp', module='autogenerated_output'):
        self.dir = dir
        self.module = module
        self.output_file = os.path.join(self.dir,'%s.%s' % (self.module, self.extension))
        self.ensure_output_file()

    def ensure_output_file(self, overwrite=False):
        if not os.path.exists(self.output_file):
            return True
        if overwrite:
            os.remove(self.output_file)
            return True
        raise Exception("This module already exists.  Please remove it to continue")

    def generate(self, project):
        data = self._prepare_data(Dict(project))
        stuff = self.template.render(data)
        file = open(self.output_file, 'wr')
        file.write(stuff)
        file.close()

    def _prepare_data(self, project):
        return {'project':project}

class PythonStubs(AutomagicGenerator):
    extension = 'py'
    template = get_template('python.py')

    def _prepare_data(self, project):
        def arg_string(endpoint):
            args = []
            args.extend([arg_repr(arg) for arg in endpoint.sequential])
            args.extend([arg_repr(arg, True) for arg in endpoint.named])
            return ', '.join(args)

        def arg_repr(arg, named=False):
            if named:
                return '='.join([str(arg.name), str(None)])
            return arg.name

        sections = []
        for section in project.sections:
            section_dict = {
                'name':section.name,
                'identifier':section.identifier,
                'description':section.description,
                'endpoints': []
            }
            endpoints = {}
            for ep in section.endpoints:
                current = endpoints.setdefault(ep.function_name, Dict({'sequential':[],'named':{}}))
                # Preserve order...it's super important
                if len(ep.sequential) > len(current.sequential):
                    current.sequential = ep.sequential
                current.named.update(dict([(arg.name, arg) for arg in current.named]))
            section_dict['endpoints'] = [{'function_name':name, 'args':arg_string(args)} for name, args in endpoints.iteritems()]
            sections.append(section_dict)

        project.sections = sections
        return Dict({'project':project})


class JSClient(AutomagicGenerator):
    extension = 'js'
    template = get_template('javascript.js')

class SphinxDocs(object):
    extension = 'rst'
    template = get_template('sphinx.rst')
